# Generated by Django 4.1 on 2022-08-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='publication ici', max_length=10000)),
                ('image', models.ImageField(help_text='image', null=True, upload_to='images')),
                ('video', models.FileField(help_text='video', null=True, upload_to='videos')),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Post',
                'ordering': ['datetime__minute'],
            },
        ),
    ]
