# Generated by Django 4.1 on 2022-08-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categorie',
            field=models.CharField(blank=True, choices=[('', ''), ('Py', 'python'), ('Js', 'JavaScript'), ('Dj', 'django'), ('Css', 'css3'), ('Html', 'html'), ('Java', 'java'), ('Annonce', 'annonce'), ('Autres', 'autres')], max_length=300, null=True),
        ),
    ]
