# Generated by Django 4.1 on 2022-08-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorie',
            field=models.CharField(blank=True, choices=[('', ''), ('Python', 'python'), ('JavaScript', 'JavaScript'), ('Django', 'django'), ('Css 3', 'css3'), ('Html 5', 'html'), ('Java ', 'java'), ('Annonce ', 'annonce'), ('Autres ', 'autres')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, help_text='video', null=True, upload_to='videos'),
        ),
    ]
