# Generated by Django 4.1 on 2022-08-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-datetime',)},
        ),
    ]
