# Generated by Django 4.1 on 2022-08-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorie',
            field=models.CharField(blank=True, choices=[('', ''), ('python', 'python'), ('javascript', 'javascript'), ('django', 'django'), ('css3', 'css3'), ('html', 'html'), ('java ', 'java'), ('annonce ', 'annonce'), ('autres ', 'autres')], max_length=300, null=True),
        ),
    ]
