# Generated by Django 4.1 on 2022-08-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0009_remove_comment_active_alter_comment_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='post',
            name='pdf',
            field=models.FileField(blank=True, help_text='pdf', null=True, upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categorie',
            field=models.CharField(blank=True, choices=[('', ''), ('python', 'python'), ('javascript', 'javascript'), ('django', 'django'), ('css3', 'css3'), ('html', 'html'), ('java', 'java'), ('annonce', 'annonce'), ('autres', 'autres')], max_length=300, null=True),
        ),
    ]
