# Generated by Django 4.1 on 2022-08-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0011_alter_post_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pdf',
        ),
        migrations.AddField(
            model_name='post',
            name='document_pdf',
            field=models.FileField(blank=True, help_text='pdf', null=True, upload_to='document_pdf'),
        ),
        migrations.AddField(
            model_name='post',
            name='document_video',
            field=models.FileField(blank=True, help_text='video', null=True, upload_to='document_video'),
        ),
    ]
