# Generated by Django 4.1 on 2022-08-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0012_remove_post_pdf_post_document_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matier', models.CharField(blank=True, choices=[('', ''), ('python', 'python'), ('javascript', 'javascript'), ('django', 'django'), ('css3', 'css3'), ('html', 'html'), ('java', 'java')], help_text='selection la matier svp', max_length=300, null=True)),
                ('pdf_cours', models.FileField(help_text='selectionner le cours concerner', upload_to='cours/')),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cours',
                'ordering': ('-datetime',),
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='document_pdf',
            field=models.FileField(blank=True, help_text='pdf', null=True, upload_to='document_pdf/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='document_video',
            field=models.FileField(blank=True, help_text='video', null=True, upload_to='document_video/'),
        ),
    ]
