# Generated by Django 4.1 on 2022-08-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0013_cours_alter_post_document_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='name',
            field=models.CharField(default='cours python', help_text='Non du document cest tres important pour les eleves', max_length=400),
        ),
    ]
