# Generated by Django 4.0 on 2022-08-20 16:59

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0014_cours_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
