# Generated by Django 4.0 on 2022-08-22 11:18

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0018_alter_comment_email_alter_comment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('datatime', models.DateTimeField(auto_now_add=True)),
                ('message', django_quill.fields.QuillField()),
            ],
            options={
                'db_table': 'Email',
                'ordering': ('-datatime',),
            },
        ),
    ]
