# Generated by Django 4.0 on 2022-08-23 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='email', max_length=254)),
                ('telephone', models.IntegerField(help_text='telephone')),
                ('profession', models.CharField(help_text='profession', max_length=100)),
                ('photo', models.ImageField(default='profile_image/profile_default.png', help_text='photo profile', upload_to='profile_image/')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
