# Generated by Django 4.0 on 2022-08-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_profession_alter_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(choices=[('Etudiant', 'Etudiant'), ('Professeur', 'Professeur')], default='Amatteur', max_length=100),
        ),
    ]
